mcyc/mufasa

mufasa/slab_sort.py

Integrated slab_sort.py into the master branch

Integrate slab_sort.py into the master branch

---

mufasa/master_fitter.py

Adds "Written by MUFASA at {time}" to history keyword of fits files saved with hdr2D in master_2comp_fit
Requires importing time.ctime

Update history key of saved FITS files

---

mufasa/UltraCube.py

Special thanks to @taiwithers for pointing these bugs out.

Merge minor bug fixes on UltraCube

---

mufasa/UltraCube.py
mufasa/aic.py
mufasa/deblend_cube.py
mufasa/guess_refine.py
mufasa/master_fitter.py
mufasa/moment_guess.py
mufasa/multi_v_fit.py
mufasa/spec_models/ammonia_multiv.py
mufasa/utils/map_divide.py
mufasa/utils/mufasa_log.py
mufasa/utils/multicore.py

also some modifications to logging....and some edits to avoid mainly division by zero errors, but also some other stuff? I'm so sorry this is such a mess....

improve multicore selection

---

mufasa/UltraCube.py

…o rss and AICc can still be computed

Assume the flat baseline model when model doesn't exist

---

mufasa/UltraCube.py
mufasa/guess_refine.py
mufasa/master_fitter.py

Fixed `refit_bad_2comp()` in `master_fitter.py`, which addressed the following issues:
1. https://github.com/mcyc/mufasa/issues/2
2. https://github.com/mcyc/mufasa/issues/59
3. https://github.com/mcyc/mufasa/issues/72
4. https://github.com/mcyc/mufasa/issues/73

Fixed refit_bad_2comp() in master_fitter

---

mufasa/multi_v_fit.py

Fixed the starting position invalid bug encountered in `cubefit_simp()`, addressing https://github.com/mcyc/mufasa/issues/22.

Fixed the starting position invalid bug

---

mufasa/UltraCube.py

This merge addresses the following issues:
1. https://github.com/mcyc/mufasa/issues/104
2. https://github.com/mcyc/mufasa/issues/103

Fixed a model comparison bug and improved the lnk sensitivity

---

mufasa/master_fitter.py
mufasa/utils/neighbours.py

Specifically, the 'best_neighbour' method has been added to `refit_bad_2comp()` to use the fitted values of the nearest neighbor with the highest lnk20 value as the new guess.

Implemented nearest neighbours guesses

---

setup.py

Updated the version number and one of the installation requirements

Version number change

---

mufasa/convolve_tools.py
mufasa/deblend_cube.py
mufasa/moment_guess.py
mufasa/multi_v_fit.py
mufasa/utils/neighbours.py

Comparisons are now performed using the best practices for literals, None, and NaNs.

Comparisons now performed using the best practices 

---

mufasa/master_fitter.py

Changed lnk_thresh default to -5 for refit_bad_2comp

---

mufasa/master_fitter.py
mufasa/multi_v_fit.py

…ld not result in unexpected fail at the first (test) fit

Patch for initial fit fail with pyspeckit's fiteach for snr > 0

---

mufasa/UltraCube.py
mufasa/master_fitter.py

Improved in-code documentation with more complete and comprehensive docstrings

Added more comprehensive docstrings to master_fitter.py and UltraCube.py

---

mufasa/UltraCube.py
mufasa/master_fitter.py
mufasa/multi_v_fit.py

Enabled better, more descriptive fits headers when saving files. There's also a bug fix with the UltraCubePlus class

Enabled better, more descriptive fits headers when saving files

---

mufasa/UltraCube.py
mufasa/convolve_tools.py
mufasa/master_fitter.py
mufasa/multi_v_fit.py
mufasa/signals.py

Improved memory efficiency with moment and snr estimates using `dask`. Should also addressed a bug that `MUFASA` had with running larger cubes.

Improved memory efficiency with moment and snr estimates

---

mufasa/master_fitter.py

Implemented functions to expand the pre-existing fits spatially, using them as initially guesses.

Implemented functions to expand the pre-existing fits spatially

---

mufasa/UltraCube.py

Ensured at least one successful fit before calling `get_modecube()` in `fit_cube()`

Ensured at least one successful fit before calling get_modecube()

---

mufasa/UltraCube.py
mufasa/master_fitter.py
mufasa/spec_models/meta_model.py
mufasa/visualization/scatter_3D.py

Adopted `MetaModel` into the `UltraCube` class as an attribute  and enabled `MetaModel`'s `peakT()` function for computing peakT in `scatter_3D.py`

Adopted MetaModel into UCube and enabled MetaModel's peakT() function

---

mufasa/UltraCube.py
mufasa/spec_models/meta_model.py

Patched a large cube unit conversion bug, that effects both dask-enabled and dask-disabled `SpectralCube`

Patched a large cube unit conversion bug

---

mufasa/UltraCube.py

A patch has been implemented to help `to_K()` handle different errors using wrappers

Patch to how to_K() handles errors

---

mufasa/UltraCube.py

Enabled get_best_2c_parcube() in UltraCube.py to return lnk maps with nan values where there was no fit. Also added has_fit() method to the UltraCube class

Ensured nan value in the saved lnk maps for pixels with no model fits

---

mufasa/convolve_tools.py

Ensure the UnitScaleError import is forward compatible

---

docs/source/tutorials/save_results.rst
mufasa/_metadata.py
mufasa/master_fitter.py

`master_fitter`'s `save_best_2comp_fit()` now saves a .cvs of the best model parameters and a .HTML for a 3D scatter plot of the modelled vlsr in position-position-velocity space

Save structured data & 3D-scatter

---

.readthedocs.yaml
docs/requirements.txt
docs/source/conf.py
docs/source/guides.rst
docs/source/installation.rst
pyproject.toml
setup.py

Updated dependencies (including pyspeckit>=1.0.4) and included pyproject.toml

Updated dependency and adopting pyproject.toml
